# Generated by Django 2.0.4 on 2018-04-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumId', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumComent',
            new_name='AlbumId',
        ),
    ]
